"""appointment capacity and contact fields

Revision ID: 041c4c34397e
Revises: 583bf4815ff8
Create Date: 2026-02-12 16:04:47.255052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041c4c34397e'
down_revision = '583bf4815ff8'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    appointments_cols = {c["name"] for c in inspector.get_columns("appointments")}
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        if "responder_name" not in appointments_cols:
            batch_op.add_column(sa.Column('responder_name', sa.String(length=255), nullable=True))
        if "responder_email" not in appointments_cols:
            batch_op.add_column(sa.Column('responder_email', sa.String(length=255), nullable=True))
        if "responder_phone" not in appointments_cols:
            batch_op.add_column(sa.Column('responder_phone', sa.String(length=80), nullable=True))

    portal_cols = {c["name"] for c in inspector.get_columns("portal_settings")}
    if "max_appointments_per_day" not in portal_cols:
        with op.batch_alter_table('portal_settings', schema=None) as batch_op:
            batch_op.add_column(sa.Column('max_appointments_per_day', sa.Integer(), nullable=False, server_default='10'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_settings', schema=None) as batch_op:
        batch_op.drop_column('max_appointments_per_day')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('responder_phone')
        batch_op.drop_column('responder_email')
        batch_op.drop_column('responder_name')

    # ### end Alembic commands ###
