"""add portal settings

Revision ID: 583bf4815ff8
Revises: 1a71b13f5054
Create Date: 2026-02-12 15:20:29.943299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583bf4815ff8'
down_revision = '1a71b13f5054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=255), nullable=True),
    sa.Column('orientation_date', sa.String(length=120), nullable=True),
    sa.Column('orientation_address', sa.String(length=255), nullable=True),
    sa.Column('orientation_phone', sa.String(length=80), nullable=True),
    sa.Column('representative_name', sa.String(length=255), nullable=True),
    sa.Column('appointment_slots', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portal_settings')
    # ### end Alembic commands ###
